### ISSUE TITLE
Belgian Keyboard

### ISSUE THREAD

**Issue by chipcat** [BlueArduino20/LocaleKeyboard.BAT#1]
Hi,

I used your LacaleKeyboard.BAT to create a belgian cpp. The problem is that it doesn't write "@ [ ]"
Can you please check this issue

**Comment by adamff-dev** [comment]
Hi, thanks for using this software.
You should see this Wiki: https://github.com/Nurrl/LocaleKeyboard.js/wiki/How-to-create-a-locale-%3F
I hope it can help. :)
